import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SupabaseProvider from './api/supabase-provider'
import LeftSide from './components/left';
import Right from './components/right'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-full flex justify-center items-center relative bg-black">
          <div className="xl:max-w-[70vw] w-full h-full flex relative">
            <LeftSide />
            <SupabaseProvider>{children}</SupabaseProvider>
            <Right />
          </div >
        </div >
      </body>
    </html>
  )
}
